#!/bin/sh
set -eu

. "${ENV_FILE:-/etc/altserver-native.env}"

service_name="${IPHONE_WIFI_MAC}@${IPHONE_UDID}"

exec avahi-publish-service "$service_name" _apple-mobdev2._tcp 62078 --host=iphone-alt.local
